{{- $version := include "imageVersion" $ }}
{{- if .Values.rbac.enabled }}
{{- if or
       (semverCompare ">=v3.1.0-0" $version)
       (not .Values.rbac.namespaced)
       (and .Values.rbac.namespaced .Values.providers.kubernetesIngress.enabled (not .Values.providers.kubernetesIngress.disableIngressClassLookup))
}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "traefik.clusterRoleName" . }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "traefik.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "traefik.serviceAccountName" . }}
    namespace: {{ template "traefik.namespace" . }}
{{- end -}}
{{- end -}}
