---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "comfyui.fullname" . }}-model-{{ .Release.Namespace }}-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: {{ .Values.volume.model.hostPath }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "comfyui.fullname" . }}-model-{{ .Release.Namespace }}-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: {{ include "comfyui.fullname" . }}-model-{{ .Release.Namespace }}-pv

# TMP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "comfyui.fullname" . }}-tmp-{{ .Release.Namespace }}-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volume.tmp.hostPath }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "comfyui.fullname" . }}-tmp-{{ .Release.Namespace }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: {{ include "comfyui.fullname" . }}-tmp-{{ .Release.Namespace }}-pv
